### ISSUE TITLE
Плавающий краш

### ISSUE THREAD

**Issue by dafatov** [dafatov/DeusBotApp#91]
```Sep 25 10:33:57 PM  [Log][   info][        player][301783183828189184]: Начало воспроизведения следующей композиции: Thousand Foot Krutch: War of Change (Official Music Video)
Sep 25 10:36:28 PM  [Log][   info][       command][301783183828189184]: [play][add]: Композиция успешно добавлена в очередь
Sep 25 10:36:28 PM  [Log][   info][       command][301783183828189184]: Команда "play" выполнена
Sep 25 10:36:30 PM  [Log][   info][        player][301783183828189184]: Была пропущена композиция: Thousand Foot Krutch: War of Change (Official Music Video)
Sep 25 10:36:31 PM  [Log][   info][       command][301783183828189184]: [skip]: Композиция была успешно пропущена
Sep 25 10:36:31 PM  [Log][   info][       command][301783183828189184]: Команда "skip" выполнена
Sep 25 10:36:35 PM  [Log][   info][        player][301783183828189184]: Начало воспроизведения следующей композиции: Слишком
Sep 25 10:38:19 PM  [Log][   info][       command][301783183828189184]: [play][add]: Композиция успешно добавлена в очередь
Sep 25 10:38:20 PM  [Log][   info][        player][301783183828189184]: Была пропущена композиция: Слишком
Sep 25 10:38:20 PM  [Log][   info][       command][301783183828189184]: Команда "play" выполнена
Sep 25 10:38:21 PM  [Log][   info][       command][301783183828189184]: [skip]: Композиция была успешно пропущена
Sep 25 10:38:21 PM  [Log][   info][       command][301783183828189184]: Команда "skip" выполнена
Sep 25 10:38:25 PM  [Log][   info][        player][301783183828189184]: Начало воспроизведения следующей композиции: Pretty U (예쁘다)
Sep 25 10:40:30 PM  [Log][   info][       command][301783183828189184]: [play][add]: Композиция успешно добавлена в очередь
Sep 25 10:40:30 PM  [Log][   info][       command][301783183828189184]: Команда "play" выполнена
Sep 25 10:40:32 PM  [Log][   info][        player][301783183828189184]: Была пропущена композиция: Pretty U (예쁘다)
Sep 25 10:40:33 PM  [Log][   info][       command][301783183828189184]: [skip]: Композиция была успешно пропущена
Sep 25 10:40:33 PM  [Log][   info][       command][301783183828189184]: Команда "skip" выполнена
Sep 25 10:40:37 PM  [Log][   info][        player][301783183828189184]: Начало воспроизведения следующей композиции: Gemstone
Sep 25 10:42:44 PM  [Log][   info][        player][301783183828189184]: Была пропущена композиция: Gemstone
Sep 25 10:42:45 PM  [Log][   info][       command][301783183828189184]: [skip]: Композиция была успешно пропущена
Sep 25 10:42:45 PM  [Log][   info][       command][301783183828189184]: Команда "skip" выполнена
Sep 25 10:42:48 PM  /opt/render/project/src/src/main/js/db/repositories/queue.js:52
Sep 25 10:42:48 PM      await db.query('UPDATE queue SET index = index - 1 WHERE guild_id=$1 AND index>$2', [guildId, target.index]);
Sep 25 10:42:48 PM                                                                                                           ^
Sep 25 10:42:48 PM  
Sep 25 10:42:48 PM  TypeError: Cannot read properties of undefined (reading 'index')
Sep 25 10:42:48 PM      at /opt/render/project/src/src/main/js/db/repositories/queue.js:52:106
Sep 25 10:42:48 PM      at runMicrotasks (<anonymous>)
Sep 25 10:42:48 PM      at processTicksAndRejections (node:internal/process/task_queues:96:5)
Sep 25 10:42:48 PM      at async module.exports.transaction (/opt/render/project/src/src/main/js/db/dbUtils.js:6:20)
Sep 25 10:42:48 PM      at async Object.module.exports.remove (/opt/render/project/src/src/main/js/db/repositories/queue.js:47:10)
Sep 25 10:42:48 PM      at async AudioPlayer.<anonymous> (/opt/render/project/src/src/main/js/actions/player.js:271:18)```

Судя по коду такое может произойти, если нет индекса 1 в очереди, но тогда это не должно быть возможно, при не пустой очереди, а это проверяется до удаления... Значит индексы сбились

**Comment by dafatov** [comment]
Не воспроизводилось и не повторяется до текущего момента
